## Removing Duplicate Values

In [7]:
import pandas as pd

In [8]:
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'SF']
})

In [9]:
data

    Name  Age City
0  Alice   25   NY
1    Bob   30   LA
2  Alice   25   NY
3  David   40   SF

In [10]:
data = data.drop_duplicates(subset=['Name', 'Age'], keep='first')

In [11]:
data

    Name  Age City
0  Alice   25   NY
1    Bob   30   LA
3  David   40   SF