In [70]:
import pandas as pd

In [71]:
data = pd.read_csv('/content/iris.csv')

In [72]:
data.isnull().sum()

sepal_length    0
sepal_width     1
petal_length    0
petal_width     1
species         1
dtype: int64

In [73]:
data['sepal_width'].fillna(data['sepal_width'].mean(), inplace = True)

<ipython-input-73-37db0d6cacb2>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['sepal_width'].fillna(data['sepal_width'].mean(), inplace = True)

In [74]:
data['petal_width'].fillna(data['petal_width'].mean(), inplace = True)

<ipython-input-74-22c331c6b0e5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['petal_width'].fillna(data['petal_width'].mean(), inplace = True)

In [75]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         1
dtype: int64

In [76]:
data['species'].fillna('setosa', inplace = True)

<ipython-input-76-788047480b8c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['species'].fillna('setosa', inplace = True)

In [77]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [78]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1     3.500000           1.4     0.200000  setosa
1           4.9     3.000000           1.4     0.200000  setosa
2           4.7     3.200000           1.3     1.205369  setosa
3           4.6     3.053691           1.5     0.200000  setosa
4           5.0     3.600000           1.4     0.200000  setosa

In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
le = LabelEncoder()

In [81]:
labels = le.fit_transform(data['species'])

In [82]:
data['species'] = labels

In [83]:
data['species'].unique()

array([0, 1, 2])

In [84]:
X = data.iloc[:,:1]

In [85]:
X

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [86]:
y = data.loc[:,['species']]

In [87]:
y

     species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

In [88]:
from sklearn.model_selection import train_test_split as tts

In [89]:
X_train,X_test, y_train, y_test = tts(X,y, test_size = 0.2, random_state = 44)

In [90]:
X_train.shape

(120, 1)

In [91]:
y_train.shape

(120, 1)

In [92]:
X_test.shape

(30, 1)

In [93]:
y_test.shape

(30, 1)

In [94]:
from sklearn.linear_model import LogisticRegression

In [95]:
model = LogisticRegression()

In [96]:
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [97]:
y_pred = model.predict(X_test)

In [98]:
y_pred

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0, 1, 0, 0, 2, 2, 0, 2, 1, 1,
       1, 0, 1, 0, 0, 2, 0, 2])

In [99]:
y_test

     species
144        2
9          0
79         1
95         1
104        2
47         0
118        2
107        2
102        2
90         1
17         0
52         1
46         0
101        2
28         0
3          0
105        2
65         1
32         0
110        2
71         1
134        2
149        2
98         1
142        2
106        2
23         0
58         1
41         0
76         1

In [100]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score

In [101]:
ac = accuracy_score(y_test, y_pred)

In [102]:
ac

0.6666666666666666

In [103]:
cm = confusion_matrix(y_test, y_pred)

In [104]:
cm

array([[9, 0, 0],
       [1, 4, 4],
       [1, 4, 7]])

In [105]:
fs = f1_score(y_test, y_pred, average = 'weighted')

In [106]:
fs

0.6546547314578005

In [107]:
ps = precision_score(y_test, y_pred, average = 'weighted')

In [108]:
ps

0.65

In [109]:
rs = recall_score(y_test, y_pred, average = 'weighted')

In [110]:
rs

0.6666666666666666