In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\Salary_dataset.csv")

In [6]:
data.drop('Unnamed: 0', inplace = True, axis = 1)

In [14]:
data.head()

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [8]:
data2 = data.copy()

In [16]:
X.head()

   YearsExperience
0              1.2
1              1.4
2              1.6
3              2.1
4              2.3

In [18]:
y.head()

    Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [19]:
X.shape

(30, 1)

In [20]:
y.shape

(30, 1)

In [21]:
data2.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.413333   76004.000000
std           2.837888   27414.429785
min           1.200000   37732.000000
25%           3.300000   56721.750000
50%           4.800000   65238.000000
75%           7.800000  100545.750000
max          10.600000  122392.000000

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
ss = StandardScaler()

In [25]:
salary_scaled = ss.fit_transform(data2.loc[:,['Salary']])

In [29]:
salary_scaled

array([[-1.36011263],
       [-1.10552744],
       [-1.419919  ],
       [-1.20495739],
       [-1.33978143],
       [-0.71830716],
       [-0.58815781],
       [-0.79981746],
       [-0.42881019],
       [-0.69801306],
       [-0.47433279],
       [-0.74976858],
       [-0.70662043],
       [-0.70201994],
       [-0.55250402],
       [-0.29921736],
       [-0.37004264],
       [ 0.26285865],
       [ 0.19885989],
       [ 0.66547573],
       [ 0.58377993],
       [ 0.82623317],
       [ 0.93861127],
       [ 1.40274136],
       [ 1.24020308],
       [ 1.09740238],
       [ 1.51986835],
       [ 1.3590738 ],
       [ 1.72102849],
       [ 1.70177321]])

In [30]:
data2.loc[:,['Salary']] = salary_scaled

In [32]:
data2.head()

   YearsExperience    Salary
0              1.2 -1.360113
1              1.4 -1.105527
2              1.6 -1.419919
3              2.1 -1.204957
4              2.3 -1.339781

In [35]:
X = data2.loc[:,['YearsExperience']]

In [36]:
y = data2.loc[:,['Salary']]

In [39]:
from sklearn.model_selection import train_test_split as tts

In [40]:
X_train, X_test, y_train, y_test = tts(X,y, train_size = 0.8, random_state= 44)

In [42]:
X_train.shape

(24, 1)

In [43]:
X_test.shape

(6, 1)

In [44]:
y_train.shape

(24, 1)

In [45]:
y_test.shape

(6, 1)

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
model = LinearRegression()

In [48]:
model.fit(X_train, y_train)

LinearRegression()

In [50]:
y_pred = model.predict(X_test)

In [51]:
y_pred

array([[ 0.97563577],
       [ 0.60370276],
       [-1.28977436],
       [ 1.14469623],
       [-0.07253907],
       [-0.44447207]])

In [52]:
y_test

      Salary
23  1.402741
21  0.826233
2  -1.419919
24  1.240203
16 -0.370043
11 -0.749769

In [53]:
from sklearn.metrics import mean_squared_error as mse

In [54]:
mse(y_test, y_pred)

0.07328541528217371

In [55]:
X1 = data.loc[:,['YearsExperience']]

In [56]:
X1.head()

   YearsExperience
0              1.2
1              1.4
2              1.6
3              2.1
4              2.3

In [57]:
y1 = data.loc[:,['Salary']]

In [58]:
y1.head()

    Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [59]:
X1_train, X1_test, y1_train, y1_test = tts(X1, y1, train_size = 0.8, random_state=44)

In [60]:
model.fit(X1_train, y1_train)

LinearRegression()

In [61]:
y1_pred = model.predict(X1_test)

In [62]:
y1_pred

array([[102300.94525798],
       [ 92275.99310783],
       [ 41239.87307071],
       [106857.74168987],
       [ 74048.80738029],
       [ 64023.85523014]])

In [64]:
y1_test

      Salary
23  113813.0
21   98274.0
2    37732.0
24  109432.0
16   66030.0
11   55795.0

In [66]:
from sklearn.metrics import mean_squared_error as mse

In [68]:
mse(y1_test, y1_pred)

53241800.09831994