In [71]:
import pandas as pd

In [72]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\iris_dataset.csv")

In [73]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            NaN           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [74]:
data.drop('Id', axis = 1, inplace = True)

In [75]:
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            NaN           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [76]:
data.dropna()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
5              5.4           3.9            1.7           0.4     Iris-setosa
..             ...           ...            ...           ...             ...
144            6.7           3.3            5.7           2.5  Iris-virginica
145            6.7           3.0            5.2           2.3  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[119 rows x 5 columns]

In [77]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              NaN           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           NaN            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [78]:
data.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     139.000000    143.000000     142.000000    141.000000
mean        5.841727      3.050350       3.780282      1.198582
std         0.820472      0.432789       1.777728      0.763262
min         4.400000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.400000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  139 non-null    float64
 1   SepalWidthCm   143 non-null    float64
 2   PetalLengthCm  142 non-null    float64
 3   PetalWidthCm   141 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [80]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [81]:
data['SepalLengthCm'] = data['SepalLengthCm'].fillna(data['SepalLengthCm'].mean())

In [82]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0         5.100000           3.5            1.4           0.2     Iris-setosa
1         4.900000           3.0            1.4           0.2     Iris-setosa
2         4.700000           3.2            1.3           0.2     Iris-setosa
3         5.841727           3.1            1.5           0.2     Iris-setosa
4         5.000000           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145       6.700000           3.0            5.2           2.3  Iris-virginica
146       6.300000           NaN            5.0           1.9  Iris-virginica
147       6.500000           3.0            5.2           2.0  Iris-virginica
148       6.200000           3.4            5.4           2.3  Iris-virginica
149       5.900000           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [83]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0         5.100000           3.5            1.4           0.2     Iris-setosa
1         4.900000           3.0            1.4           0.2     Iris-setosa
2         4.700000           3.2            1.3           0.2     Iris-setosa
3         5.841727           3.1            1.5           0.2     Iris-setosa
4         5.000000           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145       6.700000           3.0            5.2           2.3  Iris-virginica
146       6.300000           NaN            5.0           1.9  Iris-virginica
147       6.500000           3.0            5.2           2.0  Iris-virginica
148       6.200000           3.4            5.4           2.3  Iris-virginica
149       5.900000           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [84]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     7
PetalLengthCm    8
PetalWidthCm     9
Species          0
dtype: int64

In [85]:
data[data['SepalWidthCm'].isnull()].index

Index([14, 30, 49, 78, 124, 133, 146], dtype='int64')

In [86]:
import warnings 
warnings.filterwarnings('ignore')

In [87]:
data['SepalWidthCm'] = data['SepalWidthCm'].fillna(method = 'bfill')

In [88]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0         5.100000           3.5            1.4           0.2     Iris-setosa
1         4.900000           3.0            1.4           0.2     Iris-setosa
2         4.700000           3.2            1.3           0.2     Iris-setosa
3         5.841727           3.1            1.5           0.2     Iris-setosa
4         5.000000           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145       6.700000           3.0            5.2           2.3  Iris-virginica
146       6.300000           3.0            5.0           1.9  Iris-virginica
147       6.500000           3.0            5.2           2.0  Iris-virginica
148       6.200000           3.4            5.4           2.3  Iris-virginica
149       5.900000           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [89]:
data['SepalWidthCm'].isnull().sum()

0

In [90]:
data.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    8
PetalWidthCm     9
Species          0
dtype: int64

In [91]:
data['PetalLengthCm'] = data['PetalLengthCm'].fillna(method = 'ffill')

In [92]:
data.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     9
Species          0
dtype: int64

In [93]:
data['PetalWidthCm'] = data['PetalWidthCm'].fillna(data['PetalWidthCm'].mode())

In [94]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0         5.100000           3.5            1.4           0.2     Iris-setosa
1         4.900000           3.0            1.4           0.2     Iris-setosa
2         4.700000           3.2            1.3           0.2     Iris-setosa
3         5.841727           3.1            1.5           0.2     Iris-setosa
4         5.000000           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145       6.700000           3.0            5.2           2.3  Iris-virginica
146       6.300000           3.0            5.0           1.9  Iris-virginica
147       6.500000           3.0            5.2           2.0  Iris-virginica
148       6.200000           3.4            5.4           2.3  Iris-virginica
149       5.900000           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [95]:
data.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     9
Species          0
dtype: int64

In [96]:
import numpy as np

In [98]:
df = pd.DataFrame({
    "A" : [1,2,3,4,5,np.nan,9,2,1,5,np.nan,6,43,566,33],
    "B" : [1,2,3,4,5,np.nan,9,2,1,5,np.nan,6,43,566,33]
})

In [99]:
df

        A      B
0     1.0    1.0
1     2.0    2.0
2     3.0    3.0
3     4.0    4.0
4     5.0    5.0
5     NaN    NaN
6     9.0    9.0
7     2.0    2.0
8     1.0    1.0
9     5.0    5.0
10    NaN    NaN
11    6.0    6.0
12   43.0   43.0
13  566.0  566.0
14   33.0   33.0

In [100]:
df.isnull().sum()

A    2
B    2
dtype: int64

In [101]:
df = df.fillna(50)

In [102]:
df

        A      B
0     1.0    1.0
1     2.0    2.0
2     3.0    3.0
3     4.0    4.0
4     5.0    5.0
5    50.0   50.0
6     9.0    9.0
7     2.0    2.0
8     1.0    1.0
9     5.0    5.0
10   50.0   50.0
11    6.0    6.0
12   43.0   43.0
13  566.0  566.0
14   33.0   33.0