In [24]:
import pandas as pd

In [25]:
data = pd.read_csv('/content/iris.csv')

In [26]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          NaN     setosa
3             4.6          NaN           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2        NaN
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [27]:
data['sepal_width'].fillna(data['sepal_width'].mean(), inplace=True)

<ipython-input-27-5fd4e0180136>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['sepal_width'].fillna(data['sepal_width'].mean(), inplace=True)

In [28]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     1
species         1
dtype: int64

In [29]:
data['petal_width'].fillna(0.2,inplace= True)

<ipython-input-29-4d151cbf8a96>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['petal_width'].fillna(0.2,inplace= True)

In [30]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1     3.500000           1.4          0.2     setosa
1             4.9     3.000000           1.4          0.2     setosa
2             4.7     3.200000           1.3          0.2     setosa
3             4.6     3.053691           1.5          0.2     setosa
4             5.0     3.600000           1.4          0.2        NaN
..            ...          ...           ...          ...        ...
145           6.7     3.000000           5.2          2.3  virginica
146           6.3     2.500000           5.0          1.9  virginica
147           6.5     3.000000           5.2          2.0  virginica
148           6.2     3.400000           5.4          2.3  virginica
149           5.9     3.000000           5.1          1.8  virginica

[150 rows x 5 columns]

In [31]:
data['species'].fillna('setosa', inplace=True)

<ipython-input-31-4fe20c67d6e1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['species'].fillna('setosa', inplace=True)

In [32]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1     3.500000           1.4          0.2     setosa
1             4.9     3.000000           1.4          0.2     setosa
2             4.7     3.200000           1.3          0.2     setosa
3             4.6     3.053691           1.5          0.2     setosa
4             5.0     3.600000           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7     3.000000           5.2          2.3  virginica
146           6.3     2.500000           5.0          1.9  virginica
147           6.5     3.000000           5.2          2.0  virginica
148           6.2     3.400000           5.4          2.3  virginica
149           5.9     3.000000           5.1          1.8  virginica

[150 rows x 5 columns]

In [33]:
X = data.iloc[:,:-1]

In [34]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1     3.500000           1.4          0.2
1             4.9     3.000000           1.4          0.2
2             4.7     3.200000           1.3          0.2
3             4.6     3.053691           1.5          0.2
4             5.0     3.600000           1.4          0.2
..            ...          ...           ...          ...
145           6.7     3.000000           5.2          2.3
146           6.3     2.500000           5.0          1.9
147           6.5     3.000000           5.2          2.0
148           6.2     3.400000           5.4          2.3
149           5.9     3.000000           5.1          1.8

[150 rows x 4 columns]

In [37]:
y = data.iloc[:,-1]

In [38]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [39]:
from sklearn.model_selection import train_test_split as tts

In [40]:
X_train, X_test, y_train, y_test = tts(X, y, train_size=0.8, random_state = 44)

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
model = RandomForestClassifier(n_estimators=50, criterion='gini')

In [43]:
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [44]:
y_pred = model.predict(X_test)

In [45]:
y_pred

array(['virginica', 'setosa', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'virginica', 'virginica', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'versicolor'], dtype=object)

In [46]:
y_test.values

array(['virginica', 'setosa', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'virginica', 'virginica', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa', 'versicolor'], dtype=object)

In [53]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, recall_score, precision_score

In [54]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [55]:
confusion_matrix(y_test, y_pred)

array([[ 9,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 11]])

In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.90      1.00      0.95         9
   virginica       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [58]:
recall_score(y_test, y_pred,average='weighted')

0.9666666666666667

In [59]:
f1_score(y_test, y_pred, average='weighted')

0.9668192219679634

In [61]:
precision_score(y_test, y_pred, average = 'weighted')

0.9700000000000001