In [28]:
import pandas as pd

In [29]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\iris2.csv")

In [30]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [31]:
X = data.iloc[:,:4]

In [32]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [33]:
y = data.iloc[:,4]

In [34]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [35]:
from sklearn.model_selection import train_test_split as tts

In [36]:
X_train,X_test, y_train, y_test = tts(X,y, train_size = 0.8, random_state = 1)

In [37]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
..            ...          ...           ...          ...
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
72            6.3          2.5           4.9          1.5
140           6.7          3.1           5.6          2.4
37            4.9          3.1           1.5          0.1

[120 rows x 4 columns]

In [38]:
y_train

91     versicolor
135     virginica
69     versicolor
128     virginica
114     virginica
          ...
133     virginica
137     virginica
72     versicolor
140     virginica
37         setosa
Name: species, Length: 120, dtype: object

In [39]:
len(X_test)

30

In [40]:
y_test.size

30