In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    [25000,200,30.5],
    [18000,150,12.5],
    [9000,100,25.7],
    [40000,300,21.2]
    ],
    columns=['A','B','C']
                 )

In [3]:
df

       A    B     C
0  25000  200  30.5
1  18000  150  12.5
2   9000  100  25.7
3  40000  300  21.2

In [4]:
df_copy = df.copy()

In [5]:
df_copy

       A    B     C
0  25000  200  30.5
1  18000  150  12.5
2   9000  100  25.7
3  40000  300  21.2

In [6]:
for col in df_copy.columns:
    df_copy[col] = (df[col] - df[col].mean()) / df[col].std()

In [7]:
df_copy

          A         B         C
0  0.152795  0.146385  1.047946
1 -0.381987 -0.439155 -1.302587
2 -1.069565 -1.024695  0.421137
3  1.298757  1.317465 -0.166496

In [30]:
df_copy2 = df.copy()

In [31]:
df_copy2

       A    B     C
0  25000  200  30.5
1  18000  150  12.5
2   9000  100  25.7
3  40000  300  21.2

In [32]:
for col in df_copy2.columns:
    df_copy2['A'] = (df_copy2['A'] - df_copy2['A'].mean()) / df_copy2['A'].std()

In [33]:
df_copy2

          A    B     C
0  0.152795  200  30.5
1 -0.381987  150  12.5
2 -1.069565  100  25.7
3  1.298757  300  21.2