In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\social_ads.csv")

In [4]:
data2 = data.copy()

In [5]:
data2

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [6]:
ss = StandardScaler()

In [7]:
scaled_all = ss.fit_transform(data2)

In [8]:
data2[:] = scaled_all

In [9]:
data2

          Age  EstimatedSalary  Purchased
0   -1.781797        -1.490046  -0.745936
1   -0.253587        -1.460681  -0.745936
2   -1.113206        -0.785290  -0.745936
3   -1.017692        -0.374182  -0.745936
4   -1.781797         0.183751  -0.745936
..        ...              ...        ...
395  0.797057        -0.844019   1.340598
396  1.274623        -1.372587   1.340598
397  1.179110        -1.460681   1.340598
398 -0.158074        -1.078938  -0.745936
399  1.083596        -0.990844   1.340598

[400 rows x 3 columns]

In [11]:
data3 = data.copy()

In [12]:
data3

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [14]:
scaled_salary = ss.fit_transform(data3[['EstimatedSalary']])

In [15]:
data3['scaled_salary'] = scaled_salary

In [16]:
data3

     Age  EstimatedSalary  Purchased  scaled_salary
0     19            19000          0      -1.490046
1     35            20000          0      -1.460681
2     26            43000          0      -0.785290
3     27            57000          0      -0.374182
4     19            76000          0       0.183751
..   ...              ...        ...            ...
395   46            41000          1      -0.844019
396   51            23000          1      -1.372587
397   50            20000          1      -1.460681
398   36            33000          0      -1.078938
399   49            36000          1      -0.990844

[400 rows x 4 columns]

In [17]:
data3.drop('EstimatedSalary',axis=1,inplace = True)

In [18]:
data3

     Age  Purchased  scaled_salary
0     19          0      -1.490046
1     35          0      -1.460681
2     26          0      -0.785290
3     27          0      -0.374182
4     19          0       0.183751
..   ...        ...            ...
395   46          1      -0.844019
396   51          1      -1.372587
397   50          1      -1.460681
398   36          0      -1.078938
399   49          1      -0.990844

[400 rows x 3 columns]

In [19]:
data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]