In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\iris_dataset.csv")

In [3]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,NaN,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,NaN,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
data.drop('Id',axis=1,inplace=True)

In [6]:
data.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [7]:
data.columns = ['Sepal_L','Sepal_W','Petal_L','Petal_W','Species']

In [8]:
data

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
3        NaN      3.1      1.5      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
data.drop(3,axis=0,inplace = True)

In [10]:
data

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

In [11]:
data.dropna()

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
144      6.7      3.3      5.7      2.5  Iris-virginica
145      6.7      3.0      5.2      2.3  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[119 rows x 5 columns]

In [12]:
data

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

In [14]:
data.dropna(thresh = 4)

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[145 rows x 5 columns]

In [15]:
data.dropna(how = 'all')

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

In [17]:
"""how='any' (default):
Drops a row or column if any of its values are missing (NaN).
how='all':
Drops a row or column only if all of its values are missing (NaN)."""
data.dropna(subset = 'Species')

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

In [18]:
data

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      NaN      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

In [19]:
data.dropna(inplace = True)

In [20]:
data

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
144      6.7      3.3      5.7      2.5  Iris-virginica
145      6.7      3.0      5.2      2.3  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[119 rows x 5 columns]

In [21]:
data.dropna(axis = 1)

     Sepal_L  Sepal_W  Petal_L  Petal_W         Species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
5        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
144      6.7      3.3      5.7      2.5  Iris-virginica
145      6.7      3.0      5.2      2.3  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[119 rows x 5 columns]